version: '3.3'
services:
  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: mssql
    hostname: mssql
    environment:
      SA_PASSWORD: "saPass1234"
      ACCEPT_EULA: "Y"     
    restart: unless-stopped 
    ports:
      - "1433:1433"
    volumes:
      - sql_data_volume:/var/opt/mssql
  api:
    build: .
    # environment:
    #   TZ: "Asia/Dhaka"
    ports:
      - "80:80"
    depends_on:
      - db
    
volumes: 
    sql_data_volume:
    
    
